### PR TITLE
Add childcare information to travel page

### PR DESCRIPTION
**Pull request by mrmundt**
## Description
This adds information about drop-in childcare for the conference.

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jsubida

### CODE REVIEW

**Comment by mrmundt** [comment]
The URL failure seems to be intermittent.

**Comment by jbteves** [comment]
I want to approve but I can't see the flyer since GitHub won't preview binaries, can you include it on a comment?

**Comment by mrmundt** [comment]
Screen Shot 2023-07-18 at 15 47 48

**Comment by jbteves** [comment]
I thought this was our flyer, not theirs 🤣
Thanks anyway.

**Review by jbteves — APPROVED** [review]

**Pull request merged**
