### PR TITLE
Add COVID policy to website

### PR DESCRIPTION
**Pull request by mrmundt**
## Description

We have implemented a mask mandate. This PR adds the information to the website.

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves-sandia @jsubida

### CODE REVIEW

**Comment by mrmundt** [comment]
Preview: https://output.circle-artifacts.com/output/job/9acdc117-1a0f-479b-9469-07f20bdcf761/artifacts/0/usrse.github.io/usrse23/attend/index.html

**Comment by sstevens2** [comment]
Should we have a person to contact with questions or to confirm exception?

**Review by e10harvey — APPROVED** [review]

**Comment by jdamerow** [comment]
I think that makes sense! Maybe we add "If you have questions, please contact the organizers at usrsecon2023@easychair.org."?

**Review by lbianchi-lbl — CHANGES_REQUESTED** [review]
(I think this is perfectly fine as-is; just using "Request changes" to prevent it from merging automatically, so feel free to dismiss my review to get around that)

I'm thinking whether it would make sense to create a dedicated page (so that it shows up at e.g. `https://us-rse.org/usrse23/attend/covid` or even `https://us-rse.org/usrse23/attend/health`, and then link to it from the post and `/attend` page.

**Comment by cferenba** [comment]
> I think that makes sense! Maybe we add "If you have questions, please contact the organizers at [usrsecon2023@easychair.org](mailto:usrsecon2023@easychair.org)."?

I'd suggest using a usrse.org address rather than an easychair one.  Otherwise this sounds like a good idea.

**Comment by jdamerow** [comment]
I don't think we have one for the conference. This address is the one currently on the website. But I might be wrong.

**Comment by mrmundt** [comment]
All, I added a unique page (still left it on the main attend page so there is lesser chance of it being missed). I also added the email as a link.

**Comment by mrmundt** [comment]
Preview: https://output.circle-artifacts.com/output/job/9acdbc71-79f0-47d4-b019-8682bc3ee543/artifacts/0/usrse.github.io/usrse23/attend/health/index.html

**Pull request merged**
