### PR TITLE
Add instructions for previewing locally

### LINKED ISSUE #5: Add development instructions
I cloned the repo and could not find instructions for how to build or develop the site locally, so I naively tried a `docker build` that failed on [line 4 of the Dockerfile](https://github.com/USRSE/usrse23/blob/main/Dockerfile#L4) because there is no `Gemfile.lock` file. Also there is obviously a missing line that copies in the source files. Can someone explain how to build and run the site locally? I'd be happy to contribute this documentation once I demonstrate the workflow to do so.

### PR DESCRIPTION
**Pull request by mrmundt**
## Description

Fixes #5 .

## Motivation and Context

We don't want to assume that people know how to view the site locally. This adds instructions.

## Checklist:

- [x] I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [ ] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot

### CODE REVIEW

**Comment by manning-ncsa** [comment]
Thanks. I tried following your instructions but they failed me. I modified the Dockerfile and Gemfile in an attempt [to share a reproducible procedure](https://github.com/manning-ncsa/usrse23/tree/preview-site#previewing-the-site-locally-using-docker) here. Perhaps you can checkout my fork's branch and we can get the build working in the container.

**Comment by mrmundt** [comment]
@manning-ncsa - Just curious, what was your failure message? Also, I am not very well-versed in Docker, not gonna lie, and I have lots of proxy issues with it through my corporate firewall, but I'll do my best.

**Comment by manning-ncsa** [comment]
Since you shouldn't need any ingress to the container, I think your firewall should not cause trouble. The container does need to download packages, etc, but that should look like your host machine to the network. Here is what I see:

```
$ docker build -t us-rse-website:latest .
[+] Building 19.3s (8/8) FINISHED                                                                                  
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 131B                                                                          0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for docker.io/jekyll/jekyll:latest                                               0.3s
 => [internal] load build context                                                                             0.0s
 => => transferring context: 104.17kB                                                                         0.0s
 => CACHED [1/3] FROM docker.io/jekyll/jekyll@sha256:400b8d1569f118bca8a3a09a25f32803b00a55d1ea241feaf5f904d  0.0s
 => [2/3] COPY ./ ./                                                                                          0.0s
 => [3/3] RUN bundle install                                                                                 17.8s
 => exporting to image                                                                                        1.1s
 => => exporting layers                                                                                       1.1s
 => => writing image sha256:69d1f7ae07df43836414c05d2ba2c3c2f7948bdf208d42974d0818ee46f2b904                  0.0s 
 => => naming to docker.io/library/us-rse-website:latest                                                      0.0s 
                                                                                                                   
$ docker run --rm -it -p 4000:4000 us-rse-website:latest 
Configuration file: /srv/jekyll/_config.yml
jekyll 3.9.3 | Error:  tried to create Proc object without a block
/usr/gem/gems/faraday-0.15.4/lib/faraday/options.rb:166:in `new': tried to create Proc object without a block (ArgumentError)
	from /usr/gem/gems/faraday-0.15.4/lib/faraday/options.rb:166:in `memoized'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday/options.rb:247:in `<class:ProxyOptions>'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday/options.rb:229:in `<module:Faraday>'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday/options.rb:1:in `<top (required)>'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:80:in `require'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:80:in `block in require_libs'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:79:in `each'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:79:in `require_libs'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:242:in `<module:Faraday>'
	from /usr/gem/gems/faraday-0.15.4/lib/faraday.rb:16:in `<top (required)>'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer/agent.rb:1:in `require'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer/agent.rb:1:in `<top (required)>'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `require'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `block in <top (required)>'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `each'
	from /usr/gem/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `<top (required)>'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit/connection.rb:1:in `require'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit/connection.rb:1:in `<top (required)>'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit/client.rb:1:in `require'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit/client.rb:1:in `<top (required)>'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit.rb:1:in `require'
	from /usr/gem/gems/octokit-4.22.0/lib/octokit.rb:1:in `<top (required)>'
	from /usr/gem/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata.rb:4:in `require'
	from /usr/gem/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata.rb:4:in `<top (required)>'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/external.rb:58:in `require'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/external.rb:55:in `each'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/plugin_manager.rb:42:in `block in require_theme_deps'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/plugin_manager.rb:40:in `each'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/plugin_manager.rb:40:in `require_theme_deps'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/plugin_manager.rb:20:in `conscientious_require'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/site.rb:114:in `setup'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/site.rb:32:in `initialize'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `each'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `start'
	from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/gem/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
	from /usr/gem/bin/jekyll:25:in `load'
	from /usr/gem/bin/jekyll:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
``

**Comment by mrmundt** [comment]
Please add instructions on installing and configuring Docker.

**Comment by manning-ncsa** [comment]
You need a standard Docker installation that you can find instructions for starting at https://docs.docker.com/get-docker for your operating system.

**Comment by mrmundt** [comment]
> You need a standard Docker installation that you can find instructions for starting at https://docs.docker.com/get-docker for your operating system. Once installed, those commands I showed above should result in the same output.

Sorry, my point was, put these instructions in the README on your fork. It's good to link directly to installation instructions so folks don't have to go searching for the "right ones."

**Comment by jbteves** [comment]
@manning-ncsa a few things:
1. If you believe that a dockerfile is an issue, could you please raise an issue and draft a pull request to close it? This will greatly speed and ease communication because we will have the issue documented and a proposed solution with clean patch to review.
2. Docker can be fickle in normal circumstances, and further complicated behind corporate firewalls. We should generally avoid requiring it if we can, so the first step is testing whether jekyll operates without it.
3. If you follow the PR's instructions outside of docker, do they work? If not, what is the error message in this case? This way we can isolate the problems specific to this PR. If we find problems out of scope, we can raise issues separately to track and resolve them cleanly. Your error report appears to be only within the bounds of docker calls.

**Review by mchenry — APPROVED** [review]

**Comment by manning-ncsa** [comment]
@jbteves I jumped to Docker because if I can reproduce her instructions there, then I know others can reproduce them, as opposed to only being able to say "works on my machine". But I take your point, and so I will merge this request and then open a new issue specific to Docker-based development.

**Comment by jbteves** [comment]
@manning-ncsa you did not respond to my questions in point (3): do the instructions work on your machine? Please do not merge pull requests when there is still some confusion as to a problem.
@mchenry I see you approved the PR, thanks for the review. Did the instructions work on your machine?

**Review by cabejackson — COMMENTED** [review]
LGTM! These instructions were easy to follow and worked for me once I had the right gemfile. Thanks @mrmundt!!

**Comment by manning-ncsa** [comment]
> you did not respond to my questions in point (3): do the instructions work on your machine? Please do not merge pull requests when there is still some confusion as to a problem.

Her instructions are what I implemented in the Dockerfile as discussed in issue #8 , and since they worked for me there (Docker is a local process on my machine after all, and I'm not going to install all the jekyll stuff on my host machine), it was sufficient for me to merge the PR, bolstered by Kenton's approval. From your perspective, however, this was not obvious, so apologies for the confusion.

**Pull request merged**
