### PR TITLE
Add BoF, Tutorial, and Workshop information to Program dropdown

### PR DESCRIPTION
**Pull request by mrmundt**
## Description
This PR adds the currently available program data for BoFs, Workshops, and Tutorials that have been accepted.

I say "currently available" because some data is not yet here due to revisions/etc.

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jsubida

### CODE REVIEW

**Comment by mrmundt** [comment]
Program Dropdown

Workshops

BoFs

Tutorials

**Comment by manning-ncsa** [comment]
@mrmundt Perhaps this is a convoluted workflow, but I created a [pull request](https://github.com/mrmundt/usrse23/pull/1) to your fork where I added a similar base page for Program as exists for Attend. I built and verified the changes in Docker locally. If you merge into your branch it should update this pull request.

**Review by cabejackson — APPROVED** [review]
LGTM!!

**Comment by mrmundt** [comment]
> @mrmundt Perhaps this is a convoluted workflow, but I created a [pull request](https://github.com/mrmundt/usrse23/pull/1) to your fork where I added a similar base page for Program as exists for Attend. I built and verified the changes in Docker locally. If you merge into your branch it should update this pull request.

I intentionally left that page "non-existent" for right now. Once we know more about the program, we can add it in, but since we have no specifics about it at-large, I didn't want people to go looking for them on what seems like a logical page. Does that make sense?

**Pull request merged**
