### PR TITLE
added sponsor page

### PR DESCRIPTION
**Pull request by mmshad**
## Description

This is the initial push of the Sponsor page. It needs review with the main Google Doc and a good place in the website for visibility. 

## Motivation and Context

This is required for US-RSE 2023 conference. 

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jscubida

### CODE REVIEW

**Review by mrmundt — APPROVED** [review]

**Comment by jdamerow** [comment]
Looks good to me! Just two things: has `sponsor-contact@us-rse.org` been created? (just want to make sure emails are not bouncing :). And also, should we attached a pdf of this for download?

**Comment by cosden** [comment]
Yes, I made it. I can't remember if we ever tested it. I'll try now from an email address not on the list.

**Comment by jdamerow** [comment]
Jup, the email worked, thanks! 👍

**Comment by mrmundt** [comment]
> Looks good to me! Just two things: has `sponsor-contact@us-rse.org` been created? (just want to make sure emails are not bouncing :). And also, should we attached a pdf of this for download?

I think it would be a good idea to do so, yes. It makes it easier to share the information in an email.

**Pull request merged**
