### PR TITLE
Add Submission Details

### PR DESCRIPTION
**Pull request by mrmundt**
## Description
This PR adds the link to the EasyChair submission page, plus links/a page for templates, and puts a blog post about it so it can be picked up by RSS feeds (thanks, @manning-ncsa !)

## Motivation and Context
We want people to actually be able to submit!

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jscubida

### CODE REVIEW

**Comment by mrmundt** [comment]
Per @sandragesing , I have been asked to not merge this yet.

**Comment by mrmundt** [comment]
Previews:

Screen Shot 2023-03-21 at 13 29 45
------
Screen Shot 2023-03-21 at 13 43 56
------
Screen Shot 2023-03-21 at 13 44 06

**Review by manning-ncsa — APPROVED** [review]
The blog post looks good, thanks.

**Review by jdamerow — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
