### PR TITLE
Add social button for Matrix

### PR DESCRIPTION
**Pull request by manning-ncsa**
## Description

This update adds a social button to the footer linking to the Matrtix room `#us-rse-con-2023:matrix.org` (one of two existing rooms in the `#us-rse:matrix.org` Matrix Space), using for the sake of simplicity a direct link to the Matrix.org hosted Element client web app, allowing people without a Matrix account to view the public room. 

## Motivation and Context
The RSE community is more likely than most to have encountered and have experience using Matrix, given its growing popularity among for example open source projects who have transitioned from IRC to this decentralized, open protocol. Honetly I think it will add some "street cred" to the RSE conference website :-)  

On a practical level it provides another way for people to receive "push notifications" of announcements if they choose, by joining the room and setting their notification level appropriately. (We could use one of Matrix's many bridges to potentially automate mirroring announcements from [the US-RSE Slack channel](https://matrix.org/bridges/#slack) or from [the announcement email list](https://matrix.org/bridges/#email), but that discussion is outside the scope of this PR.)

See https://matrix.org/faq/#what-is-matrix and https://decentci.ncsa.illinois.edu/what-is-matrix/ to learn more about what Matrix is.

## Checklist:
- [ ] I have posted the link for the PR in the usrse slack (#usrse-2023-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @mrmundt @cabejackson @manning-ncsa @jmelot @jbteves @jscubida

### CODE REVIEW

**Comment by jbteves** [comment]
I live under a rock, what the heck is Matrix?

**Comment by manning-ncsa** [comment]
> I live under a rock, what the heck is Matrix?

Check my links in the description. They are good starting points.

**Comment by mrmundt** [comment]
I think this PR Is fine, but we haven't used Matrix before for US-RSE, so I'm hesitant to merge it. @jdamerow , @sandragesing , any thoughts?

**Comment by jdamerow** [comment]
I haven't heard of Matrix before, so not sure. If people think it's useful, I'd say sure why not. Maybe it's a question for the steering committee?

**Comment by manning-ncsa** [comment]
My heart will not be broken if the decision is to decline; however, it may be helpful to weigh the pros and cons. One pro is that there will be "yet another communication channel" to potentially reach more people about the conference since it is the first one and not well established within the professional community. Another pro is that the presence on Matrix will no doubt strike a positive note in the minds of some fraction of RSEs, as there is strong overlap of potential conference attendees and people who embrace free and open source software and its principles. Additionally, the overhead is extremely low. Matrix "rooms" are free in the same way emails are free. A con would be content moderation: kicking people/bots and deleting offensive posts (that I volunteer to do along with any other volunteers), but I would be shocked if content moderation becomes a burden. If it did I would say drop the room and move on!

**Comment by mrmundt** [comment]
@manning-ncsa - Alright, we have some questions:
 
1. What is the overall goal of having the Matrix room?
2. What is the long-term plan (e.g., is it just for the conference, or would the intent to be creating a long-lasting US-RSE presence)?
3. How many moderators are necessary / what would you expect the level of interaction to be from the community?

You list as a pro that there is yet another avenue for communication, and we (SC / Outreach WG) don't always see that as a pro. It can add additional burden as it's yet another thing that we have to monitor, maintain, etc. We absolutely agree with your second pro, however, that there is surely a subset of RSEs who would react positively to a presence such as this.

**Comment by manning-ncsa** [comment]
> * What is the overall goal of having the Matrix room?

The overall goal of the Matrix room is to offer a free, open source, modern, and decentralized platform for the RSE community to receive announcements about the conference and to communicate with one another about it.

> * What is the long-term plan (e.g., is it just for the conference, or would the intent to be creating a long-lasting US-RSE presence)?

If people use the platform and like what it offers, then it would be a good idea to continue using Matrix long-term as a communication tool when it makes sense to do so. As I said above, Matrix rooms are essentially as cheap and easy as emails are. Due to its proprietary nature, Slack does not seem to be a very stable platform for organizations like US-RSE, in terms of changing cost structures, changing terms of service, and uncertainty about who is or will be allowed to join channels. It may be a good idea to have a backup plan.

> * How many moderators are necessary / what would you expect the level of interaction to be from the community?

I do not know how many moderators would be necessary, nor do I have a good way to predict the level of interaction. My assumption is that the vast majority of people would behave professionally given the context as they do in the Slack workspace. There are only 1,500 people in the "general" channel on the US-RSE Slack workspace, and I would assume the fraction who would also use Matrix (or would prefer it to Slack) would be small, at least in the short term. However, the US-RSE community is growing, as is the population of people who use Matrix around the world, so I would expect it to grow over time. If the room(s) became a source of stress or moderation became too challenging, it/they could be easily disabled and dissociated from the organization.

**Comment by manning-ncsa** [comment]
I thought of this conversation today after a colleague mentioned that [Gitter has transitioned to using Matrix](https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/) as of this month. If you are also unfamiliar with [Gitter](https://gitter.im/), it is a popular developer community chat system, used by the communities of some massive projects including [Node](https://gitter.im/nodejs/home), [TypeScript](https://gitter.im/Microsoft/TypeScript), [Angular](https://gitter.im/angular/home), [Scala](https://gitter.im/scala/home)  ([ref](https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix?ref=gitter)). I'm mentioning it here as more evidence that it is a real thing that software developers know and use instead of some hobby project of mine :smile:

**Comment by mrmundt** [comment]
@manning-ncsa - We've decided that we do not want to implement this at this time. We don't believe we have sufficient capacity to support another mechanism for communication for the US-RSE at large, and until we do, we don't want it supported for only part of US-RSE's many offerings. We appreciate the suggestion and will look into it again in the future when we have better capacity!

**Pull request closed without merging**
